### PR TITLE
Update PHP72 version

### PR DESCRIPTION
**Pull request by kraileth**

### CODE REVIEW

**Comment by kraileth** [comment]
This one is wrong. Repology got confused by some obscure windows PHP stuff in two Windows repos. It doesn't look like there's a real 7.2.7, yet.

**Comment by jrmarino** [comment]
you should usually leave these updates to me anyway because it requires a regeneration of 50+ ports via script.  The ones with versions in Ravenports (versus ravensource) are always a bit special.

**Comment by kraileth** [comment]
Ah, ok. I'll leave those be in the future.

**Comment by kraileth** [comment]
Looks like version 7.2.7 was released one day later... It's available now.

**Pull request closed without merging**
